/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Wednesday, January 7, 2026 at 11:26:54 AM
   By task:     Import Data Wizard
   
   Source file: Viya_ServerLocation_SASServer:
   /home/sasdemo/project1_latin1/customer.csv
   Server:      SASApp
   
   Output data: PROJECT1.CUSTOMER
   Server:      SASApp
   -------------------------------------------------------------------- */

DATA PROJECT1.CUSTOMER;
    LENGTH
        ID                 8
        Name             $ 36
        Activity         $ 18
        Country          $ 2
        Gender           $ 1
        BirthDate          8
        Issue_Lev1       $ 41
        Issue_Lev2       $ 40
        Call_Category1   $ 21
        Call_Category2   $ 20
        Resolution       $ 49
        Verbatims        $ 231 ;
    FORMAT
        ID               BEST7.
        Name             $CHAR36.
        Activity         $CHAR18.
        Country          $CHAR2.
        Gender           $CHAR1.
        BirthDate        DATE9.
        Issue_Lev1       $CHAR41.
        Issue_Lev2       $CHAR40.
        Call_Category1   $CHAR21.
        Call_Category2   $CHAR20.
        Resolution       $CHAR49.
        Verbatims        $CHAR231. ;
    INFORMAT
        ID               BEST7.
        Name             $CHAR36.
        Activity         $CHAR18.
        Country          $CHAR2.
        Gender           $CHAR1.
        BirthDate        DATE9.
        Issue_Lev1       $CHAR41.
        Issue_Lev2       $CHAR40.
        Call_Category1   $CHAR21.
        Call_Category2   $CHAR20.
        Resolution       $CHAR49.
        Verbatims        $CHAR231. ;
    INFILE "&path./&project._&encoding./customer_&encoding..csv"
        LRECL=32767
        FIRSTOBS=2
        ENCODING="LATIN1"
        DLM='2c'x
        MISSOVER
        DSD ;
    INPUT
        ID               : ?? BEST7.
        Name             : $CHAR36.
        Activity         : $CHAR18.
        Country          : $CHAR2.
        Gender           : $CHAR1.
        BirthDate        : ?? DATE9.
        Issue_Lev1       : $CHAR41.
        Issue_Lev2       : $CHAR40.
        Call_Category1   : $CHAR21.
        Call_Category2   : $CHAR20.
        Resolution       : $CHAR49.
        Verbatims        : $CHAR231. ;
    if birthdate ne . then age=floor(yrdif(birthdate,today(),'AGE'));
RUN;


proc datasets lib=project1;
modify customer; 
index create id;
index create country;
quit; 

options msglevel=i;
proc means data=project1.customer maxdec=2; 
where country="BE";
var age; 
run; 